"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { GlobalStateProvider } from "./States/GlobalStateManager";
import { Toaster } from "react-hot-toast";
import AuthProvider from "./components/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalStateProvider>
          <AuthProvider>{children}</AuthProvider>
        </GlobalStateProvider>
        <Toaster />
      </body>
    </html>
  );
}
